### ISSUE TITLE
Model 2 (not new realizations) is broken

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1120]
in the output routine. 

Here is some backtrace.

```
Time step   17 at day 280/4870, date = 07-Oct-2000
  Substep 0, stepsize 11.5 days.
Error: [/home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/NonlinearSolver_impl.hpp:154] Failed to complete a time step within 15 iterations.
Problem: Solver convergence failed, restarting solver with new time step (3.795000 days).

  Substep 0, stepsize 3.795 days.
    Substep summary: well iterations = 1, newton iterations = 6, linearizations = 7 (7.22792 sec), linear iterations = 110 (6.59058 sec)
flow_ebos: /home/kaib/OPM-master-test/debug/opm-material/opm/material/common/Tabulated1DFunction.hpp:501: std::size_t Opm::Tabulated1DFunction<Scalar>::findSegmentIndex_(Scalar) const [with Scalar = double; std::size_t = long unsigned int]: Assertion `xValues_[segmentIdx] <= x' failed.

Breakpoint 1, __GI_abort () at abort.c:51
51	abort.c: No such file or directory.
(gdb) backtrace 
#0  __GI_abort () at abort.c:51
#1  0x00007ffff36dfbd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x89088d "xValues_[segmentIdx] <= x", file=file@entry=0x887af0 "/home/kaib/OPM-master-test/debug/opm-material/opm/material/common/Tabulated1DFunction.hpp", line=line@entry=501, 
    function=function@entry=0x8ac240 <Opm::Tabulated1DFunction<double>::findSegmentIndex_(double) const::__PRETTY_FUNCTION__> "std::size_t Opm::Tabulated1DFunction<Scalar>::findSegmentIndex_(Scalar) const [with Scalar = double; std::size_t = long unsigned int]") at assert.c:92
#2  0x00007ffff36dfc82 in __GI___assert_fail (assertion=assertion@entry=0x89088d "xValues_[segmentIdx] <= x", file=file@entry=0x887af0 "/home/kaib/OPM-master-test/debug/opm-material/opm/material/common/Tabulated1DFunction.hpp", line=line@entry=501, 
    function=function@entry=0x8ac240 <Opm::Tabulated1DFunction<double>::findSegmentIndex_(double) const::__PRETTY_FUNCTION__> "std::size_t Opm::Tabulated1DFunction<Scalar>::findSegmentIndex_(Scalar) const [with Scalar = double; std::size_t = long unsigned int]") at assert.c:101
#3  0x0000000000561784 in Opm::Tabulated1DFunction<double>::findSegmentIndex_ (this=<optimized out>, x=<optimized out>) at /home/kaib/OPM-master-test/debug/opm-material/opm/material/common/Tabulated1DFunction.hpp:501
#4  0x00000000005637aa in Opm::Tabulated1DFunction<double>::eval<Opm::DenseAd::Evaluation<double, 3u> > (this=this@entry=0x1e247070, x=..., extrapolate=extrapolate@entry=true) at /home/kaib/OPM-master-test/debug/opm-material/opm/material/common/Tabulated1DFunction.hpp:267
#5  0x000000000057bc2e in Opm::WetGasPvt<double>::saturationPressure<Opm::DenseAd::Evaluation<double, 3u> > (this=<optimized out>, regionIdx=<optimized out>, temperature=..., Rv=...)
    at /home/kaib/OPM-master-test/debug/opm-material/opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp:557
#6  0x000000000057cee9 in Opm::GasPvtMultiplexer<double, true>::saturationPressure<Opm::DenseAd::Evaluation<double, 3u> > (this=<optimized out>, regionIdx=<optimized out>, temperature=..., Rv=...)
    at /home/kaib/OPM-master-test/debug/opm-material/opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp:236
#7  0x000000000057d0ee in Opm::FluidSystems::BlackOil<double>::saturationPressure<Ewoms::BlackOilFluidState<Ewoms::Properties::TTag::EclFlowProblem>, Opm::DenseAd::Evaluation<double, 3u> > (fluidState=..., phaseIdx=phaseIdx@entry=2, regionIdx=<optimized out>)
    at /home/kaib/OPM-master-test/debug/opm-material/opm/material/fluidsystems/BlackOilFluidSystem.hpp:1041
#8  0x000000000062b562 in Opm::FluidSystems::BlackOil<double>::dewPointPressure<Ewoms::BlackOilFluidState<Ewoms::Properties::TTag::EclFlowProblem>, Opm::DenseAd::Evaluation<double, 3u> > (regionIdx=<optimized out>, fluidState=...)
    at /home/kaib/OPM-master-test/debug/opm-material/opm/material/fluidsystems/BlackOilFluidSystem.hpp:1014
#9  Opm::BlackoilModelEbos::getSimulatorData (this=this@entry=0x3382e460, localState=...) at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/BlackoilModelEbos.hpp:1301
#10 0x000000000062cb66 in Opm::BlackoilOutputWriter::writeTimeStep<Opm::BlackoilModelEbos> (this=this@entry=0x1d3e56e0, timer=..., localState=..., localWellState=..., physicalModel=..., substep=substep@entry=true, nextstep=nextstep@entry=-1)
    at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp:954
#11 0x000000000068fbc2 in Opm::AdaptiveTimeStepping::stepImpl<Opm::NonlinearSolver<Opm::BlackoilModelEbos>, Opm::BlackoilState, Opm::WellStateFullyImplicitBlackoilDense, Opm::BlackoilOutputWriter> (this=this@entry=0x2580ce60, simulatorTimer=..., solver=..., state=..., 
    well_state=..., event=true, outputWriter=0x1d3e56e0, fipnum=0x7fffffffc2d0) at /home/kaib/OPM-master-test/debug/opm-simulators/opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp:309
#12 0x0000000000692853 in Opm::AdaptiveTimeStepping::step<Opm::NonlinearSolver<Opm::BlackoilModelEbos>, Opm::BlackoilState, Opm::WellStateFullyImplicitBlackoilDense, Opm::BlackoilOutputWriter> (fipnum=<optimized out>, outputWriter=..., event=<optimized out>, well_state=..., 
    state=..., solver=..., simulatorTimer=..., this=<optimized out>) at /home/kaib/OPM-master-test/debug/opm-simulators/opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp:177
#13 Opm::SimulatorFullyImplicitBlackoilEbos::run (this=<optimized out>, timer=..., state=...) at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp:316
#14 0x0000000000694fe5 in Opm::FlowMainEbos::runSimulator (this=this@entry=0x7fffffffdba0) at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/FlowMainEbos.hpp:653
#15 0x00000000006c4c90 in Opm::FlowMainEbos::execute (this=this@entry=0x7fffffffdba0, argc=argc@entry=3, argv=argv@entry=0x7fffffffdde8) at /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/FlowMainEbos.hpp:128
#16 0x0000000000504d98 in main (argc=3, argv=0x7fffffffdde8) at /home/kaib/OPM-master-test/debug/opm-simulators/examples/flow_ebos.cpp:38
```

**Comment by GitPaean** [comment]
This issue is fixed by OPM/opm-material#218 .
